### ISSUE TITLE
Unable to login to Stake with direct credential

### ISSUE THREAD

**Issue by joyceyuu** [stabacco/stake-python#143]
Hi Stefano,

Thanks for the great work you have done!

I tried approach 2 which is to use direct credential read from env variables to login but failed with below error. I'm pretty sure the credentials are correct. After checking out the link https://global-prd-api.hellostake.com/api/sessions/v2/createSession, I got following message

{"code":500,"message":"HTTP 405 Method Not Allowed"}

Dose Stake ban programatic login? I tried to dig out some documentation in Stake but couldn't find anything relevant..

`aiohttp.client_exceptions.ClientResponseError: 412, message='Precondition Failed', url=URL('https://global-prd-api.hellostake.com/api/sessions/v2/createSession')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "connect.py", line 18, in <module>
    asyncio.run(print_user(login_request))
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "connect.py", line 14, in print_user
    async with StakeClient(request) as stake_session:
  File "/Users/.virtualenvs/stake/lib/python3.8/site-packages/stake/client.py", line 212, in __aenter__
    await self.login(self._login_request)
  File "/Users/.virtualenvs/stake/lib/python3.8/site-packages/stake/client.py", line 200, in login
    raise InvalidLoginException("Invalid Login Credentials") from error
stake.client.InvalidLoginException: Invalid Login Credentials`

It would be highly appreciated if you could have a look! Thanks :)

- Joyce

**Comment by joyceyuu** [comment]
Ah I managed to login after enabling two-factor authentication. Will close this one

**Comment by stabacco** [comment]
Thanks for letting me know, I'll update the docs accordingly to the
requirements of having 2FA enabled
