### ISSUE TITLE
ASX LimitBuyRequest KeyError: 'order'

### ISSUE THREAD

**Issue by julianprester** [stabacco/stake-python#158]
LimitBuyRequests on ASX seem to have stopped working...

The code example that I'm using is:

```python
import stake
import asyncio
import pyotp

totp = pyotp.TOTP("XXXXXXXXXXXXXXX")

login_request = stake.CredentialsLoginRequest(
    username="XXXXXXXXXXXXXXX",
    password="XXXXXXXXXXXXXXX",
    otp=totp.now(),
)

async def buy(symbol: str, price: float, units: int):
    async with stake.StakeClient(
        request=login_request, exchange=stake.constant.ASX
    ) as stake_session:
        return await stake_session.trades.buy(
            stake.asx.trade.LimitBuyRequest(symbol=symbol, price=price, units=units)
        )

print(asyncio.run(buy("IVV", 42, 1)))
```

The error that I'm receiving is:

```
Traceback (most recent call last):
  File "C:\Users\julian\Development\stake-dca\stake_dca\test.py", line 21, in <module>
    print(asyncio.run(buy("IVV", 42, 1)))
  File "C:\Users\julian\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\julian\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "C:\Users\julian\Development\stake-dca\stake_dca\test.py", line 17, in buy
    return await stake_session.trades.buy(
  File "C:\Users\julian\AppData\Local\pypoetry\Cache\virtualenvs\stake-dca-mo1Xf9ZY-py3.10\lib\site-packages\stake\asx\trade.py", line 134, in buy
    return await self._trade(self._client.exchange.orders, request)
  File "C:\Users\julian\AppData\Local\pypoetry\Cache\virtualenvs\stake-dca-mo1Xf9ZY-py3.10\lib\site-packages\stake\asx\trade.py", line 108, in _trade
    return Order(**data["order"])
KeyError: 'order'
```

Other parts of the API such as `show_portfolio()` or `cash_available()` work fine.

Could be a change on the API backend as I'm almost certain that this code used to run? Any chance you can look into this?

**Comment by stabacco** [comment]
Thanks for reporting this, i'll take a look

**Comment by stabacco** [comment]
I've had a quick look and it looks like the request fails because the total order is less than 500 AUD, 
this seems to work, if fact: `print(asyncio.run(buy("IVV", 35, 20)))`. 

I'll try and do some work to surface those errors a bit better, but for now I'll close this. Please reopen if needed.

P.S. thanks for showing me the use of pyotp, I was not aware of that lib.

**Comment by julianprester** [comment]
Thank you! I wasn't aware of that limit. It seems to be working now.
