### ISSUE TITLE
Works from the interactive console, but not as a script...

### ISSUE THREAD

**Issue by thoran** [stabacco/stake-python#159]
The following works from the interactive console, but not as a script run from the command line:
```
#!/usr/bin/env python3

import asyncio
import os
import stake

from stake import CredentialsLoginRequest
from stake import SessionTokenLoginRequest
from stake import StakeClient

print(os.getenv('STAKE_TOKEN'))
login_request = SessionTokenLoginRequest()

async def print_user():
    async with StakeClient(login_request) as stake_session:
        print(stake_session.user.first_name)
        print(stake_session.headers.stake_session_token)

asyncio.run(print_user())
```
When I run it as a script I get the following:
```
Traceback (most recent call last):
  File "/Users/thoran/bin/stake.py", line 5, in <module>
    import stake
  File "/Users/thoran/bin/stake.py", line 7, in <module>
    from stake import CredentialsLoginRequest
ImportError: cannot import name 'CredentialsLoginRequest' from partially initialized module 'stake' (most likely due to a circular import) (/Users/thoran/bin/stake.py)
```
What am I doing wrong?

P.S. Thanks for writing this!

**Comment by stabacco** [comment]
Did you name your file stake.py? That might be the problem. Try renaming it
and see if it works.

**Comment by thoran** [comment]
Indeed that was the issue! Thanks.
